### ISSUE TITLE
[Nominations Open] Most Valuable Sigstore Contributor Award 2022 🏆

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#123]
This issue is to receive nominations for the Most Valuable Sigstore Contributor Award 2022.

This award recognizes excellence of technical contributions to Sigstore. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to Sigstore and why they should win.

Nomination Deadline: Tuesday, September 20, 2022

More details are available here: https://github.com/sigstore/community/tree/main/awards

**Comment by puerco** [comment]
I would like to nominate Priya Wadhwa @priyawadhwa as Most Valuable Sigstor Contributor :tada: 

It is hard to put in words how much better the project is because of Priya's work: from her code contributions, to doing a superb job evangelizing with her great presentations all over the place, and lately doing an outstanding job moving the GA effort forward. I can't thank her enough. I'm sorry for the excess of adjectives, but I need them.

Disclaimer: I'm a coworker of her, but I've been learning from Priya and have been amazed by her work way, way before our company even existed. Thank you Priya.

**Comment by hectorj2f** [comment]
It is really hard to choose the most valuable contributor, I could nominate several contributors. However I'd like to nominate Carlos Panato Tadeu @cpanato as Most Valuable Sigstore Contributor 🎖️.

Carlos is involved in almost all the sigstore projects and he is always available to help on Slack. His contributions keep the projects in a healthy and robust state.
