### ISSUE TITLE
Sigstore Logo revisions

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#239]
There is an update to the Sigstore logo to deal with a copyright issue. The TSC has approved the updated logo. 
We are waiting to get updated design files and then this issue will track updating the logo in all relevant locations.

**Comment by tracymiranda** [comment]
We will have an update logo with an updated hand drawn seal - design files incoming!

**Comment by tracymiranda** [comment]
The new logos have been received and merged here: https://github.com/sigstore/community/pull/248

**Comment by tracymiranda** [comment]
List of places to update

- [ ] Sigstore website + ico
- [ ] Github
- [ ] YouTube
- [ ] Twitter
- [ ] LinkedIn
- [ ] OpenSSF
- [ ] Landscape

**Comment by philpennock** [comment]
- [ ] Slack emojis

**Comment by sandipanpanda** [comment]
Hi, I am interested in helping in this effort, and I am working on it.

**Comment by sandipanpanda** [comment]
@tracymiranda I see that a number of logo references are breaking due to the use of capitalization in directory names, for example, from `/artwork/sigstore/horizontal/color%20reverse/sigstore_horizontal-colorreverse.png` to `/artwork/Sigstore/Horizontal/Color%20Reverse/sigstore_horizontal-colorreverse.png`. So can we just change the directory names to lowercase as they were before https://github.com/sigstore/community/pull/248/files to avoid changing icon references like [this](https://github.com/sigstore/gitsign/pull/274/files) down the line?

**Comment by haydentherapper** [comment]
I've updated https://status.sigstore.dev/

**Comment by haydentherapper** [comment]
This should now be complete. Social media (linkedin, youtube, twitter) were already updated, as were the OpenSSF landscape and landing pages. I have updated the website, docs, and blog. search.sigstore.dev was also updated with the new Rekor logo.
