### ISSUE TITLE
Assignment of active issues

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/community#44]
As a new contributor, I want to track what is actively being worked on so that I can find new issues to implement. Due to access restrictions around assignment of issues, individual contributors cannot self-assign issues.

At a bare minimum, I propose that we update community guidelines to ask contributors to comment on an issue when they're actively developing. If a developer cannot complete a feature, they should update the issue so that another contributor can work on it.

I propose that we also investigate tooling around self-assignment of issues.

Context: [New contributor friction log](https://docs.google.com/document/d/1HagEnvYF-aHvRt0oh6_YLdCvic9pmU2KfzO7TUek4_4/edit?resourcekey=0-HngMnlcaCXZnR5MU5oqSXw)

**Comment by dlorenc** [comment]
I really get the sentiment here but I've never seen this work in practice due to limitations in Github tooling. I haven't found a decent workflow to even see all the issues assigned to me :(

One fun idea that's worked is to do triage parties, where you get a few people together and just burn through stale issues. You can sort by old, new, or random.

There's even a cool tool called triage party to help crowd source this.

**Comment by haydentherapper** [comment]
Now with two years of context, I know this is hard to do with GH tooling. We can add active community members into the org with triage permissions in projects they're active in as per the community guidelines.
